### ISSUE TITLE
Add new event interface breaks if required fields not present on save

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/road_closings#97] opened 2015-10-23 17:05 UTC
Rather than giving details about what fields are required, the page comes back with an incomplete form.

**Comment by charlesbrandt** [comment] 2015-10-23 17:10
"Sorry You did not include all the required fields" pops up at a later page. This is with a title, start and end date only.

**Comment by inghamn** [comment] 2015-10-23 17:13
Duplicate of #92

**Closed as completed** 2015-10-26 14:58 UTC
