### ISSUE TITLE
Waze format data export

### ISSUE THREAD

**Issue by rbdietz** [City-of-Bloomington/road_closings#71] opened 2015-08-17 18:12 UTC
Configure output to export into Waze format.

**Comment by inghamn** [comment] 2015-09-22 13:21
The waze feed format is documented here:
http://blog.waze.com/p/connected-citizens-partner-feeds-specs.html

**Comment by rbdietz** [comment] 2015-09-25 01:11
Regex isn't a good long-term solution but if it works then we are good for the time being.

**Comment by hiesterd** [comment] 2015-09-25 13:14
My guess is, a better long-term solution would be to change the drawing interface such that the drawings inherently create the data needed by Waze—it's a duplicate of data entry to have both a _hand-written copy_ of the roads scheduled for closure, and a _drawing_ of the roads scheduled for closure.

**Closed as completed** 2015-10-26 18:20 UTC
Labels: enhancement
